config/routes.rb
  ClientVisit::Application.routes.draw do
    

  match "visit/agenda" => "visits#agenda", :as => :agenda
  match "visit/data" => "visits#data", :as => :data
  match "visit/dbaction" => "visits#dbaction", :as => :dbaction

  resources :visits do
    collection do
      get :agenda
      get :data
      get :dbaction
    end
    resources :agendas
    resources :checklists
  end

    root :to => 'visits#index'

   
  resources :users, :controller => 'users'

   devise_for :users, :path_prefix => 'my' do
      get "/users/sign_out" => "devise/sessions#destroy", :as => :destroy_user_session
    end

    

  end
    

app/models/visit.rb
class Visit < ActiveRecord::Base
	attr_accessible :attachment
	attr_accessible :Agenda
	attr_accessible :Description
	attr_accessible :Date
	attr_accessible :Customers

    has_many :agendas
    has_one :checklist, :dependent => :destroy

	
	attr_accessor :attachment

	has_attached_file :attachment


end

app/controllers/visits_controller.rb
class VisitsController < ApplicationController
  # GET /visits
  # GET /visits.json
 
    def agenda
     @visit =  Visit.find(params[:visit])  
     @agenda = Agenda.where(:visit_id=> params[:visit])
     time1 = Time.new
     time1.strftime("%Y-%m-%d %H:%M:%S")
     p time1
      respond_to do |format|
      format.html
      format.csv { send_data @agenda.to_csv }
      format.xls { headers["Content-Disposition"] = "attachment; filename=\"#{@visit.Agenda}_"+"#{time1}"+".xls"}
    end
      
    end
 
    def data
     @agenda = Agenda.where(:visit_id=> params[:visit])
    end



    def dbaction
        #called for all db actions
    
    
          date = params["c0"]
          starthour = params["c1"]
          startmin =  params["c2"]
          endhour = params["c3"]
          endmin =  params["c4"]
          duration = params["c5"]
          agenda = params["c6"]
          details = params["c7"]
          clientparticipants   = params["c8"]
          tcsparticipants= params["c9"]
          

        @mode = params["!nativeeditor_status"]
        
        @id = params["gr_id"]
        case @mode
            when "inserted"
                agenda1 = Agenda.new
                agenda1.agendadate = date
                agenda1.StartTimeHour = Integer(starthour)
                agenda1.StartTimeMin = startmin.to_i
                agenda1.EndTimeHour = endhour.to_i
                agenda1.EndTimeMin = endmin.to_i
                agenda1.timeduration= duration
                agenda1.Agenda =agenda
                agenda1.Details =details
                agenda1.ClientParticipants =clientparticipants
                agenda1.TCSParticipants =tcsparticipants
                agenda1.visit_id = params[:visit]
                agenda1.save!
                
                @tid = agenda1.id
            when "deleted"
                agenda1=Agenda.find(@id)
                agenda1.destroy
                
                @tid = @id
            when "updated"
                agenda1=Agenda.find(@id)
                agenda1.agendadate = date
                agenda1.StartTimeHour = Integer(starthour)
                agenda1.StartTimeMin = startmin.to_i
                agenda1.EndTimeHour = endhour.to_i
                agenda1.EndTimeMin = endmin.to_i
                 agenda1.timeduration= duration
                
                agenda1.Agenda =agenda
                agenda1.Details =details
                agenda1.ClientParticipants =clientparticipants
                agenda1.TCSParticipants =tcsparticipants
                agenda1.visit_id = params[:visit]
                agenda1.save!
                
                @tid = @id
        end 
    end

  def index

    @visits = Visit.all
# @visits = Visit.search(params[:search]).page(params[:page]).per(5)
 
  # @visits = Visit.search(params[:search]).order(sort_column + " " + sort_direction).page(params[:page]).per(3)
  #     respond_to do |format|
  #     format.html # index.html.erb
  #     format.json { render json: @visits }
  #   end
  end



  # GET /visits/1
  # GET /visits/1.json
  def show
    @visit = Visit.find(params[:id])

    # respond_to do |format|
    #   format.html # show.html.erb
    #   format.json { render json: @visit }
    # end
  end

  # GET /visits/new
  # GET /visits/new.json
  def new
    @visit = Visit.new

    # respond_to do |format|
    #   format.html # new.html.erb
    #   format.json { render json: @visit }
    # end
  end

  # GET /visits/1/edit
  def edit
    @visit = Visit.find(params[:id])
  end

  # POST /visits
  # POST /visits.json
  def create
    @visit = Visit.new(params[:visit])

    respond_to do |format|
      if @visit.save
        format.html { redirect_to @visit, notice: 'Visit was successfully created.' }
        format.json { render json: @visit, status: :created, location: @visit }
      else
        format.html { render action: "new" }
        format.json { render json: @visit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /visits/1
  # PUT /visits/1.json
  def update
    @visit = Visit.find(params[:id])

    respond_to do |format|
      if @visit.update_attributes(params[:visit])
        format.html { redirect_to @visit, notice: 'Visit was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @visit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /visits/1
  # DELETE /visits/1.json
  def destroy
    @visit = Visit.find(params[:id])
    @visit.destroy

    respond_to do |format|
      format.html { redirect_to visits_url }
      format.json { head :no_content }
    end
  end


end

app/helpers/visits_helper.rb
module VisitsHelper

end

app/views/visits/_agenda.html.erb
      
<!-- <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
    "http://www.w3.org/TR/html4/loose.dtd"> -->
<html>
    <head>

    </head>
 
    <body>
       <center><h2>Agenda Sheet</h2></center>   <%= link_to 'Back', visits_path, :class=> 'btn' %>  <br/>


<br/>
       <center>  <div id="grid_here" style="width:1150px; height:600px;">

        </div></center>
        <script type="text/javascript" charset="utf-8">

      var deco = getUrlVars()["visit"];

 

      var grid = new dhtmlXGridObject("grid_here");
            
              
            grid.setImagePath("");
            grid.setHeader("Date,Start Time,#cspan,End Time,#cspan,Duration,Agenda,Details,Firm Participants,TCS Participants");
            grid.attachHeader(["#rspan", "HH", "MM", "HH", "MM", "#rspan","#rspan","#rspan","#rspan","#rspan"]);
            grid.enableMultiselect(true)
       
            grid.setInitWidths("100,50,50,50,50,100,150,200,200,200");
            grid.setSkin("dhx_skyblue");
            grid.enableAutoHeight(true);
            grid.enableMultiline(true);
            grid.enableEditEvents(true,false,false);
            grid.setColTypes("dhxCalendar,coro,coro,coro,coro,ro,txt,txt,txt,txt");

            var combo1 = grid.getCombo(1); 
            var combo2 = grid.getCombo(2); 
            var combo3 = grid.getCombo(3); 
            var combo4 = grid.getCombo(4); 

             combo1.put(0,"0"); 
            combo1.put(7,"7"); 
            combo1.put(8,"8"); 
            combo1.put(9,"9"); 
            combo1.put(10,"10"); 
            combo1.put(11,"11"); 
            combo1.put(12,"12"); 
            combo1.put(13,"13"); 
            combo1.put(14,"14"); 
            combo1.put(15,"15"); 
            combo1.put(16,"16"); 
            combo1.put(17,"17"); 
            combo1.put(18,"18"); 
            combo1.put(19,"19");
            combo1.put(20,"20");
            combo1.put(21,"21");
    
            combo2.put(0,"0"); 
            combo2.put(15,"15"); 
            combo2.put(30,"30"); 
            combo2.put(45,"45"); 
            
     
            combo3.put(0,"0"); 
            combo3.put(7,"7"); 
            combo3.put(8,"8"); 
            combo3.put(9,"9"); 
            combo3.put(10,"10"); 
            combo3.put(11,"11"); 
            combo3.put(12,"12"); 
            combo3.put(13,"13"); 
            combo3.put(14,"14"); 
            combo3.put(15,"15"); 
            combo3.put(16,"16"); 
            combo3.put(17,"17"); 
            combo3.put(18,"18");  
            combo3.put(19,"19");  
            combo3.put(20,"20");
            combo3.put(21,"21");  

            combo4.put(0,"0"); 
            combo4.put(15,"15"); 
            combo4.put(30,"30"); 
            combo4.put(45,"45"); 

                    
            grid.init();
      
            grid.load("/visit/data?visit="+deco)

grid.attachEvent("onEditCell",function(stage,rId,cInd,nValue,oValue){
    if (stage==1 &&  this.editor &&  this.editor.obj){
        this.editor.obj.select();
    }
    return true;
    });
           
       dp = new dataProcessor("/visit/dbaction?visit="+deco);
            dp.init(grid);

      grid.attachEvent("onEditCell",function(stage,id,ind,value){
    if (stage == 2 && (ind ==1 || ind == 2 || ind ==3 || ind == 4) ){
          //this code will be executed when edit operation finished in column with index 1
               StartTimeHour= parseInt(grid.cellById(id,1).getValue());
               StartTimeMin= parseInt(grid.cellById(id,2).getValue());
               EndTimeHour= parseInt(grid.cellById(id,3).getValue());
               
               EndTimeMin= parseInt(grid.cellById(id,4).getValue());

          
             if (EndTimeHour == StartTimeHour) 
             { if (EndTimeMin > StartTimeMin)
                { 
                  timeduration=(EndTimeMin-StartTimeMin)+" mins"
                  }
                if (EndTimeMin == StartTimeMin)
                { 
                  timeduration="Start and end time cant be same"
                  }                

                if (StartTimeMin > EndTimeMin)
                {
                  timeduration="Start Time can not be greater then End time"
                }
              }


             if ((EndTimeHour > StartTimeHour) && (EndTimeMin>=StartTimeMin) )

                  timeduration=(EndTimeHour-StartTimeHour) +"hr(s)"+(EndTimeMin-StartTimeMin)+" mins"

           if ((EndTimeHour > StartTimeHour) && (EndTimeMin<StartTimeMin) && EndTimeMin!=0 )
                   timeduration=(EndTimeHour-StartTimeHour)+" hr(s)"+(StartTimeMin-EndTimeMin)+" mins"

             if ( (EndTimeHour > StartTimeHour) && (EndTimeMin==0 && StartTimeMin!=0))
                  timeduration=(EndTimeHour-StartTimeHour-1)+" hr(s)"+(60-StartTimeMin)+" mins"

               if (EndTimeHour < StartTimeHour) 

                timeduration="Start Time can not be greater then End time"

              
   grid.cells(id,5).setValue(timeduration);
         dp = new dataProcessor("/visit/dbaction?visit="+deco);
            dp.init(grid);
          
    }
    return true;
});
            
function getUrlVars() {
    var vars = {};
    var parts = window.location.href.replace(/[?&]+([^=&]+)=([^&]*)/gi, function(m,key,value) {
        vars[key] = value;
    });
    return vars;
}

        </script>
        <% @visit=Visit.find(params[:visit]) %>
     
       <center> 
       <%= submit_tag "Add", :type => 'button', :onclick => "grid.addRow(grid.uid(),['#{@visit.Date}','0','0','0','0','0','Click to add agenda','Click to add details','Click to add FIRM participants','Click to add TCS participants'])" ,:class => "btn" %>
        <input type="button" value="Delete" onclick="grid.deleteSelectedRows()" class="btn"> 




         <%= link_to 'Export as Excel', url_for(:format => 'xls' ,:filename=> 'your_file_name.xls', :visit => params[:visit]) , :class => "btn" %></center></center>


   

    </body>

</html>


app/views/visits/_form.html.erb
<%= form_for(@visit, :html => {:multipart => true}) do |f| %>
  <% if @visit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@visit.errors.count, "error") %> prohibited this visit from being saved:</h2>

      <ul>
      <% @visit.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div style="height: 50px">
</div>
<div class="well span4">
  <div class="field"><font size="3px">Agenda :</font><br>
    <%= f.text_field :Agenda , :required => true %>
  </div>

  <div class="field" > <font size="3px">Description : </font><br>
    <%= f.text_field :Description, :required => true  %>
  </div>

<div class="field" id="Date"> <font size="3px">Date : </font><br>
  <%= f.text_field :Date , :required => true %>
</div>



  <div class="field"> <font size="3px">Customers : </font><br>
    <%= f.text_field :Customers , :required => true %>
  </div>


<div class="field"> <font size="3px">Attach File : </font><br>
    <%= f.file_field :attachment %>
  </div>

 

<div style="height: 50px">
</div>

<div>  <%= f.submit "Save", :class=> 'btn btn-primary' %></div>

</div>

<% end %>
<div class="span9">
  <%= image_tag("back-icon.png", :border => 0) %>
  <%= link_to 'Back', visits_path, :class=> 'btn' %>
</div>

app/views/visits/_visits.html.erb



<div style='min-height:200px'>
    <table  id="index_table" class="pretty">
     <thead> 
      <tr>
       
          <th style=" padding-right: 5px; padding-left: 5px; min-width: 50px"><font size="2"><b>Agenda </b></font></th>
          <th style=" padding-right: 5px; padding-left: 5px; min-width: 150px "><font size="2"><b>Description </b></font></th>
          <th style=" padding-right: 5px; padding-left: 5px; min-width: 150px "><font size="2"><b>Date</b></font></th>
          <th style=" padding-right: 5px; padding-left: 5px; min-width: 150px "><font size="2"><b>Customers </b></font></th>
          <th style=" padding-right: 5px; padding-left: 5px; min-width: 50px "><font size="2"><b>Attached File</b></font></th>
          <th style=" padding-right: 5px; padding-left: 5px; min-width: 50px "><font size="2"><b>Agenda Sheet </b></font></th>
           <th style=" padding-right: 5px; padding-left: 5px; min-width: 50px "><font size="2"><b>Checklist </b></font></th>
           <th style=" padding-right: 5px; padding-left: 5px; min-width: 50px "><font size="2"><b>Destroy </b></font></th>


      </tr>
     </thead>
      <tbody>
   <% @visits.each do |visit| %>
      <tr>
          
          <td style=" padding-right: 5px; padding-left: 5px; min-width: 50px"><%= link_to visit.Agenda, visit %></td>
          <td style=" padding-right: 5px; padding-left: 5px; min-width: 150px "><%= visit.Description %></td>
          <td style=" padding-right: 5px; padding-left: 5px; min-width: 100px "><%= visit.Date %></td>
          <td style=" padding-right: 5px; padding-left: 5px; min-width: 150px "><%= visit.Customers %></td>

        <%  if visit.attachment.blank? %>
            <td style=" padding-right: 5px; padding-left: 5px; min-width: 150px ">Not Available</td>
        <% else %>
            <td style=" padding-right: 5px; padding-left: 5px; min-width: 50px " align="center"><%= link_to(image_tag("Download-icon.png", :border => 0), visit.attachment.url)%></td>
        <% end %>
         <td style=" padding-right: 5px; padding-left: 5px; min-width: 120px ">
          <%= link_to 'Agenda Sheet', agenda_visits_path(:visit => visit.id), :class=> 'btn'%></td>


  
<% if !visit.checklist %>

 <td style=" padding-right: 5px; padding-left: 5px; min-width: 120px ">
 <%= link_to 'New Checklist',  new_visit_checklist_path(:visit_id => visit.id), :class=> 'btn' %></td>

<% else %>

  <td style=" padding-right: 5px; padding-left: 5px; min-width: 120px ">
    <%= link_to 'Edit Checklist',  edit_visit_checklist_path(:visit_id => visit.id, :id => visit.checklist.id), :class=> 'btn' %></td>
<% end %>



          <td style=" padding-right: 5px; padding-left: 5px; min-width: 50px "><b><%= link_to(image_tag("destroy.png", :border => 0), visit, confirm: 'Are you sure?', method: :delete )%></b></td>
      </tr>       


        <% end %>
      </tbody>
    </table>

  </div>
  <div align='center'>

</div>

app/views/visits/agenda.html.erb

 


	<%= render 'agenda' %></center>

app/views/visits/agenda.xls.erb


<center><table border="1" width="400">
  <tr><td colspan="2" bgcolor="#81BEF7"><h3><center>Visit Details</h3></center></td></tr>
  <tr>
    <td><b>Visit Agenda</b></td><td><%= @visit.Agenda %></td></tr>
 <tr><td><b>Visit Description</b></b></td><td><%= @visit.Description %></td></tr>
 <tr><td><b>Visit Date</b></td><td><%= @visit.Date %></td></tr>
 <tr><td><b>Customers</b></td><td><%= @visit.Customers %></td></tr>
  </tr></table></center>
  <table border="1">
          <tr><td colspan="10" ></td></tr>
      <tr><td colspan="10" bgcolor="#81BEF7"><h3><center>Agenda Sheet</center><h3></td></tr>
  <tr>
    <th>Date</th>
    <th>Start Time Hour</th>
    <th>Start Time Minute</th>
     <th>End Time Hour</th>
    <th>End Time Minute</th>
    <th>Agenda </th>
    <th>Duration</th>
    <th>Details</th>
    <th>Firm Participants</th>
    <th>TCS participants</th>
 
  </tr>

<% @agenda= Agenda.where(:visit_id=>@visit.id) %>
<% @agenda.each do |user| %>
  <tr>
    <td><%= user.agendadate %></td>
    <td><%= user.StartTimeHour %></td>
    <td><%= user.StartTimeMin %></td>
    <td><%= user.EndTimeHour %></td>
    <td><%= user.EndTimeMin %></td>
     <td><%= user.timeduration %></td>
    <td><%= user.Agenda %></td>
    <td><%= user.Details %></td>
    <td><%= user.ClientParticipants %></td>
    <td><%= user.TCSParticipants %></td>
  </tr>
<% end %>
</table>

<br />

app/views/visits/edit.html.erb
<h1>Editing visit</h1>

<%= render 'form' %>

app/views/visits/index.html.erb
<h2>Visits</h2>

  <div style="height: 50px">
  </div>


<%= form_tag visits_path, :method => 'get', :id => "visits_search" do %>


  <div id="visits">
  	<%= render 'visits' %>
  </div>
<% end %>



  <div style="height: 50px">
  </div>

<%= link_to 'New Visit', new_visit_path, :class=> 'btn  btn-custom' %>

app/views/visits/index.js.erb
$("#visits").html("<%= escape_javascript(render("visits")) %>");
$('#paginator').html('<%= escape_javascript(paginate(@visits, :remote => true).to_s) %>');

app/views/visits/new.html.erb
<h1>New visit</h1>

<%= render 'form' %>

app/views/visits/show.html.erb
  <div style=" min-height: 50px">
  </div>
<h2>Visit Details </h2><br/>
<div style="min-width: 960px; overflow:auto;">
    <table  id="show_table" >
      <thead>
     <tr>
       
          <td style=" padding-right: 5px; padding-left: 5px; padding-bottom: 5px; min-width: 50px"><font size="3"><b>Agenda </b></font></td> 
          <td style=" padding-right: 5px; padding-left: 5px; min-width: 50px"><%= @visit.Agenda %></td>
      </tr>
      <tr>
        <td style=" padding-right: 5px; padding-left: 5px;padding-bottom: 5px; min-width: 150px "><font size="3"><b>Description </b></font></td>  
        <td style=" padding-right: 5px; padding-left: 5px; min-width: 150px "><%= @visit.Description %></td>
      </tr>
      <tr>
        <td style=" padding-right: 5px; padding-left: 5px; padding-bottom: 5px;min-width: 100px "><font size="3"><b>Date </b></font></td>     
        <td style=" padding-right: 5px; padding-left: 5px; min-width: 150px "><%= @visit.Date %></td>
      </tr>
      <tr>
        <td style=" padding-right: 5px; padding-left: 5px;padding-bottom: 5px; min-width: 150px "><font size="3"><b>Customers </b></font></td> 
        <td style=" padding-right: 5px; padding-left: 5px; min-width: 70px "><%= @visit.Customers %></td>
      </tr>
      <tr> 

        <td style=" padding-right: 5px; padding-left: 5px;padding-bottom: 5px; min-width: 150px "><font size="3"><b>Attached File </b></font></td> 


        <%  if @visit.attachment.blank? %>
            <td style=" padding-right: 5px; padding-left: 5px">Not Available</td>
        <% else %>
            <td style=" padding-right: 5px; padding-left: 5px" align="center"><%= link_to(image_tag("Download-icon.png", :border => 0), @visit.attachment.url)%></td>
        <% end %>
      </tr>

 
      </thead>

    </table>
  </div>




  <br/>
 <%= link_to 'Agenda Sheet', agenda_visits_path(:visit => @visit.id), :class=> 'btn' %>





<% if !@visit.checklist %>
 <%= link_to 'Generate Checklist',  new_visit_checklist_path(@visit), :class=> 'btn' %>

<% else %>

  <td style=" padding-right: 5px; padding-left: 5px; min-width: 150px "><%= link_to 'Edit Checklist',  edit_visit_checklist_path(@visit), :class=> 'btn' %></td>
<% end %>


</br></br>




 
  <%= link_to 'Back', visits_path, :class=> 'btn' %>

  <%= link_to 'Edit', edit_visit_path(@visit), :class=> 'btn' %>