config/routes.rb
  ClientVisit::Application.routes.draw do
    

  match "visit/agenda" => "visits#agenda", :as => :agenda
  match "visit/data" => "visits#data", :as => :data
  match "visit/dbaction" => "visits#dbaction", :as => :dbaction

  resources :visits do
    collection do
      get :agenda
      get :data
      get :dbaction
    end
    resources :agendas
    resources :checklists
  end

    root :to => 'visits#index'

   
  resources :users, :controller => 'users'

   devise_for :users, :path_prefix => 'my' do
      get "/users/sign_out" => "devise/sessions#destroy", :as => :destroy_user_session
    end

    

  end
    

app/views/shared/_header.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner" style="height:60px">
    <div class="container-fluid">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">

       
      </a>
      <div class="brand" style="margin-top: 5px;"><h1><font color= "white">
        <%= link_to(image_tag("header.JPG", :border => 0), visits_path) %>
        <%#= link_to 'Client Visit Portal', visits_path %></font></h1></div>
      <div class="pull-right"  style="margin-top: 5px;">
        <% if user_signed_in? %>
          <div class="pull-right">
            <b><font color= "white" size="2px">
                Today is <%=Time.new.strftime('%a %d %b %Y')%>  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                </b></font>
                </div>
                <div class="nav-collapse">
                  <ul class="nav">
                    <li class="active"></li>

                    <li class="dropdown">
                      <a href="#"
                         class="dropdown-toggle"
                         data-toggle="dropdown"> <b><font color= "white" size="2px">
                        Welcome, <%= current_user.email %></b></font>
                        <b class="caret"></b>
                      </a>
                      <ul class="dropdown-menu">
                         <li><%= link_to 'Home', visits_path %></li>
                        <li class="divider"></li>
                        <li><%= link_to 'Edit Account', edit_user_registration_path %></li>
                        <li class="divider"></li>

                        <%  if current_user.role.to_s.downcase=='admin'%>

                        <li><%= link_to 'Manage User', users_path %></li>
                        <li class="divider"></li>
                        
                        <% end %>


                        <li> <%= link_to "Sign out", destroy_user_session_path , :method => :delete%> </li>
                      </ul>
                    </li>

                  </ul>
                </div><!--/.nav-collapse -->

              <% end %>
         
        </div>


      </div>
    </div>
  </div>