config/routes.rb
  ClientVisit::Application.routes.draw do
    

  match "visit/agenda" => "visits#agenda", :as => :agenda
  match "visit/data" => "visits#data", :as => :data
  match "visit/dbaction" => "visits#dbaction", :as => :dbaction

  resources :visits do
    collection do
      get :agenda
      get :data
      get :dbaction
    end
    resources :agendas
    resources :checklists
  end

    root :to => 'visits#index'

   
  resources :users, :controller => 'users'

   devise_for :users, :path_prefix => 'my' do
      get "/users/sign_out" => "devise/sessions#destroy", :as => :destroy_user_session
    end

    

  end
    

app/models/agenda.rb
class Agenda < ActiveRecord::Base
  attr_accessible :agendadate,:timeduration,:StartTimeHour,:EndTimeHour,:Agenda, :ClientParticipants, :Date, :Details, :TCSParticipants,:visit_id

belongs_to :visit
def self.to_csv(options = {})
    CSV.generate(options) do |csv|
      csv << column_names
      all.each do |product|
        csv << product.attributes.values_at(*column_names)
      end
    end
  end
end

app/controllers/agendas_controller.rb
class AgendasController < ApplicationController
  # GET /agendas
  # GET /agendas.json
  

  def index
    @agendas = Agenda.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @agendas }
    end
  end

  # GET /agendas/1
  # GET /agendas/1.json
  def show
    @agenda = Agenda.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @agenda }
    end
  end

  # GET /agendas/new
  # GET /agendas/new.json
  def new
    @agenda = Agenda.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @agenda }
    end
  end

  # GET /agendas/1/edit
  def edit
    @agenda = Agenda.find(params[:id])
  end

  # POST /agendas
  # POST /agendas.json
  def create
    @agenda = Agenda.new(params[:agenda])

    respond_to do |format|
      if @agenda.save
        format.html { redirect_to @agenda, notice: 'Agenda was successfully created.' }
        format.json { render json: @agenda, status: :created, location: @agenda }
      else
        format.html { render action: "new" }
        format.json { render json: @agenda.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /agendas/1
  # PUT /agendas/1.json
  def update
    @agenda = Agenda.find(params[:id])

    respond_to do |format|
      if @agenda.update_attributes(params[:agenda])
        format.html { redirect_to @agenda, notice: 'Agenda was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @agenda.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /agendas/1
  # DELETE /agendas/1.json
  def destroy
    @agenda = Agenda.find(params[:id])
    @agenda.destroy

    respond_to do |format|
      format.html { redirect_to agendas_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/agendas_helper.rb
module AgendasHelper
end

app/views/agendas/_form.html.erb
<%= form_for(@agenda) do |f| %>
  <% if @agenda.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@agenda.errors.count, "error") %> prohibited this agenda from being saved:</h2>

      <ul>
      <% @agenda.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Date %><br />
    <%= f.date_select :Date %>
  </div>
  <div class="field">
    <%= f.label :StartTime %><br />
    <%= f.time_select :StartTime %>
  </div>
  <div class="field">
    <%= f.label :EndTime %><br />
    <%= f.time_select :EndTime %>
  </div>
  <div class="field">
    <%= f.label :Duration %><br />
    <%= f.time_select :Duration %>
  </div>
  <div class="field">
    <%= f.label :Agenda %><br />
    <%= f.text_field :Agenda %>
  </div>
  <div class="field">
    <%= f.label :Details %><br />
    <%= f.text_area :Details %>
  </div>
  <div class="field">
    <%= f.label :ClientParticipants %><br />
    <%= f.text_field :ClientParticipants %>
  </div>
  <div class="field">
    <%= f.label :TCSParticipants %><br />
    <%= f.text_field :TCSParticipants %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/agendas/edit.html.erb
<h1>Editing agenda</h1>

<%= render 'form' %>

<%= link_to 'Show', @agenda %> |
<%= link_to 'Back', agendas_path %>

app/views/agendas/index.html.erb
<h1>Listing agendas</h1>

<table>
  <tr>
    <th>Date</th>
    <th>Starttime</th>
    <th>Endtime</th>
    <th>Duration</th>
    <th>Agenda</th>
    <th>Details</th>
    <th>Clientparticipants</th>
    <th>Tcsparticipants</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @agendas.each do |agenda| %>
  <tr>
    <td><%= agenda.Date %></td>
    <td><%= agenda.StartTime %></td>
    <td><%= agenda.EndTime %></td>
    <td><%= agenda.Duration %></td>
    <td><%= agenda.Agenda %></td>
    <td><%= agenda.Details %></td>
    <td><%= agenda.ClientParticipants %></td>
    <td><%= agenda.TCSParticipants %></td>
    <td><%= link_to 'Show', agenda %></td>
    <td><%= link_to 'Edit', edit_agenda_path(agenda) %></td>
    <td><%= link_to 'Destroy', agenda, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Agenda', new_agenda_path %>

app/views/agendas/new.html.erb
<h1>New agenda</h1>

<%= render 'form' %>

<%= link_to 'Back', agendas_path %>

app/views/agendas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Date:</b>
  <%= @agenda.Date %>
</p>

<p>
  <b>Starttime:</b>
  <%= @agenda.StartTime %>
</p>

<p>
  <b>Endtime:</b>
  <%= @agenda.EndTime %>
</p>

<p>
  <b>Duration:</b>
  <%= @agenda.Duration %>
</p>

<p>
  <b>Agenda:</b>
  <%= @agenda.Agenda %>
</p>

<p>
  <b>Details:</b>
  <%= @agenda.Details %>
</p>

<p>
  <b>Clientparticipants:</b>
  <%= @agenda.ClientParticipants %>
</p>

<p>
  <b>Tcsparticipants:</b>
  <%= @agenda.TCSParticipants %>
</p>


<%= link_to 'Edit', edit_agenda_path(@agenda) %> |
<%= link_to 'Back', agendas_path %>