config/routes.rb
  ClientVisit::Application.routes.draw do
    

  match "visit/agenda" => "visits#agenda", :as => :agenda
  match "visit/data" => "visits#data", :as => :data
  match "visit/dbaction" => "visits#dbaction", :as => :dbaction

  resources :visits do
    collection do
      get :agenda
      get :data
      get :dbaction
    end
    resources :agendas
    resources :checklists
  end

    root :to => 'visits#index'

   
  resources :users, :controller => 'users'

   devise_for :users, :path_prefix => 'my' do
      get "/users/sign_out" => "devise/sessions#destroy", :as => :destroy_user_session
    end

    

  end
    

app/models/checklist.rb
class Checklist < ActiveRecord::Base
  attr_accessible :GroundTransCheck, :GroundTransComment, :LaptopPassCheck, 
  					:LaptopPassComment, :ODCAccessCheck, :ODCAccessComment, 
  					:SEZPassCheck, :SEZPassComment, :TCSVisitorPassCheck, 
  					:TCSVisitorPassComment, :email, :visit_id


  belongs_to :visit
  
end

app/controllers/checklists_controller.rb
class ChecklistsController < ApplicationController
  # GET /checklists
  # GET /checklists.json
  def index
    @checklists = Checklist.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @checklists }
    end
  end

  # GET /checklists/1
  # GET /checklists/1.json
  def show
    @checklist = Checklist.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @checklist }
    end
  end

  # GET /checklists/new
  # GET /checklists/new.json
  def new
   @visit = Visit.find_by_id(params[:visit_id])
   @checklist = Checklist.new(:visit_id => params[:visit_id])

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @checklist }
    end
  end

  # GET /checklists/1/edit
  def edit
   @visit = Visit.find_by_id(params[:visit_id])
   @checklist = @visit.checklist#Checklist.new(:visit_id => params[:visit_id])

  end

  # POST /checklists
  # POST /checklists.json
  def create 
    @visit = Visit.find_by_id(params[:visit_id])
    @checklist = Checklist.new(params[:checklist].merge(:visit_id => params[:visit_id]))


    #ChecklistMailer.test(@checklist).deliver

    respond_to do |format|
      if @checklist.save
        format.html { redirect_to [@visit,@checklist], notice: 'Checklist was successfully created.' }
        format.json { render json: @checklist, status: :created, location: @checklist }
      else
        format.html { render action: "new" }
        format.json { render json: @checklist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /checklists/1
  # PUT /checklists/1.json
  def update
    @checklist = Checklist.find(params[:id])
    respond_to do |format|
      if @checklist.update_attributes(params[:checklist])
        format.html { redirect_to visit_checklist_path, notice: 'Checklist was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @checklist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /checklists/1
  # DELETE /checklists/1.json
  def destroy
    @checklist = Checklist.find(params[:id])
    @checklist.destroy

    respond_to do |format|
      format.html { redirect_to checklists_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/checklists_helper.rb
module ChecklistsHelper
end

app/views/checklists/_form.html.erb
<%= form_for([@visit, @checklist]) do |f| %>
  <% if @checklist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@checklist.errors.count, "error") %> prohibited this checklist from being saved:</h2>

      <ul>
      <% @checklist.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div style="height: 50px">
</div>

<div class="well span6">
  <table>
    <tr>
      <td>
        <font size="3px">Ground Transport :</font>
      </td>
      <td>
            <%= f.check_box(:GroundTransCheck,{}, "Required", "Not Required")%>
            <%= f.text_area :GroundTransComment, :rows=>1, :cols=>50 %></br>
      </td>
        
    </tr>

    <tr>
      <td>
        <font size="3px">Laptop Pass :</font>
      </td>
      <td>
            <%= f.check_box(:LaptopPassCheck,{}, "Required", "Not Required") %>
            <%= f.text_area :LaptopPassComment, :rows=>1, :cols=>50 %></br>
      </td>
        
    </tr>

    <tr>
      <td>
        <font size="3px">SEZ Pass         :</font>
      </td>
      <td>
            <%= f.check_box(:SEZPassCheck,{}, "Required", "Not Required") %>
            <%= f.text_area :SEZPassComment, :rows=>1, :cols=>50 %></br>
      </td>
        
    </tr>

    <tr>
      <td>
        <font size="3px">TCS Visitor Pass :</font>
      </td>
      <td>
            <%= f.check_box(:TCSVisitorPassCheck,{}, "Required", "Not Required")%>
            <%= f.text_area :TCSVisitorPassComment, :rows=>1, :cols=>50 %></br>
      </td>
        
    </tr>

    <tr>
      <td>
        <font size="3px">ODC Access       :</font>
      </td>
      <td>
            <%= f.check_box(:ODCAccessCheck,{}, "Required", "Not Required") %>
            <%= f.text_area :ODCAccessComment, :rows=>1, :cols=>50 %></br>
      </td>
        
    </tr>


            <%= hidden_field_tag :visit_id, @visit.id %>


    <tr>
      <td>
        <font size="3px">E-Mail to        :</font>

      </td>
      <td>
            &nbsp&nbsp&nbsp
            <%= f.text_area :email, :rows=>1, :cols=>50 %></br>
      </td>
    </tr>
  </table>  

<div style="height: 50px">
</div>


<div>  <%= f.submit "Save", :class=> 'btn btn-primary' %></div>
</div>


<% end %>

app/views/checklists/edit.html.erb
<h1>Editing checklist</h1>

<%= render 'form' %>


<div class="span9">
  <%= link_to 'Show', visit_checklist_path, :class=> 'btn'  %> |
  <%#= link_to 'Back', visit_path(@visit), :class=> 'btn' %>
  <%= link_to 'Back', visits_path, :class=> 'btn' %>
</div>



<%#= link_to 'Show', visit_checklist_path, :class=> 'btn'  %> 
<%#= link_to 'Back', visits_path, :class=> 'btn' %>

app/views/checklists/index.html.erb
<h1>Listing checklists</h1>

<table>
  <tr>
    <th>VISIT ID</th>
    <th>Groundtranscheck</th>
    <th>Groundtranscomment</th>
    <th>Laptoppasscheck</th>
    <th>Laptoppasscomment</th>
    <th>Sezpasscheck</th>
    <th>Sezpasscomment</th>
    <th>Tcsvisitorpasscheck</th>
    <th>Tcsvisitorpasscomment</th>
    <th>Odcaccesscheck</th>
    <th>Odcaccesscomment</th>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @checklists.each do |checklist| %>
  <tr>
    <td><%= checklist.visit_id %></td>
    <td><%= checklist.GroundTransCheck %></td>
    <td><%= checklist.GroundTransComment %></td>
    <td><%= checklist.LaptopPassCheck %></td>
    <td><%= checklist.LaptopPassComment %></td>
    <td><%= checklist.SEZPassCheck %></td>
    <td><%= checklist.SEZPassComment %></td>
    <td><%= checklist.TCSVisitorPassCheck %></td>
    <td><%= checklist.TCSVisitorPassComment %></td>
    <td><%= checklist.ODCAccessCheck %></td>
    <td><%= checklist.ODCAccessComment %></td>
    <td><%= checklist.email %></td>
    <td><%= link_to 'Show', checklist %></td>
    <td><%= link_to 'Edit', edit_checklist_path(checklist) %></td>
    <td><%= link_to 'Destroy', checklist, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>
<br />

</br>

<%= link_to 'New Checklist', new_checklist_path %>

app/views/checklists/new.html.erb
<h1>New checklist</h1>

<%= render 'form' %>

 <%#= link_to 'Back', visits_path, :class=> 'btn' %>
<div class="span9">
  <%#= link_to 'Show', visit_checklist_path, :class=> 'btn'  %> 
  <%#= link_to 'Back', visit_path(@visit), :class=> 'btn' %>
  <%= link_to 'Back', visits_path, :class=> 'btn' %>


</div>

app/views/checklists/show.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta content="text/html; charset=UTF-8" http-equiv="Content-Type" />
  </head>
  <body>
    <h1>Greetings, <%= @checklist.email %></h1>
    <h2>===============================</h2>
    <p>
      Here is the list of checklist regarding Client Visit : Visit ID-<%= @checklist.visit_id %>.<br/>
    </p>
    <p>

      Ground Transport requirement : <%= @checklist.GroundTransCheck %> <br/>
      Comment : <%= @checklist.GroundTransComment %>
    </p>

    <p>

      Laptop Pass requirement : <%= @checklist.LaptopPassCheck %> <br/>
      Comment : <%= @checklist.LaptopPassComment %>
    </p>


    <p>

      SEZ Pass requirement : <%= @checklist.SEZPassCheck %> <br/>
      Comment : <%= @checklist.SEZPassComment %>
    </p>

    <p>

      TCS Visitors Pass requirement : <%= @checklist.TCSVisitorPassCheck %> <br/>
      Comment : <%= @checklist.TCSVisitorPassComment %>
    </p>

    <p>

      ODC Access requirement : <%= @checklist.ODCAccessCheck %> <br/>
      Comment : <%= @checklist.ODCAccessComment %>
    </p>
  </br></br>


    <p>Thanks and have a great day!</p>
    <p>Regards.</p>
  </body>
</html>